# Import all node modules to trigger @register_node decorators.
from backend.nodes import (
    # IO
    colormap,
    crop_resize,
    fft_2d_inverse,
    filter_fft,
    filter_gaussian,
    filter_median,
    flip,
    font,
    image,
    image_demo,
    folder,
    coordinate,
    coordinate_pair,
    level_facet,
    level_plane,
    level_poly,
    mask_draw,
    mask_threshold,
    note,
    number,
    range_slider,
    rotate,
    save,
    edge_detect,
    colormap_adjust,
    fix_zero,
    line_correction,
    # Mask
    mask_morphology,
    mask_invert,
    mask_operations,
    grain_distance_transform,
    save_layers,
    # Correction
    scar_removal,
    # Display
    annotations,
    angle_measure,
    markup,
    preview_image,
    statistics,
    value_io,
    view_3d,
    print_table,
    curvature,
    fractal_dimension,
    histogram,
    acf_2d,
    acf_1d,
    cursors,
    fft_2d,
    psdf,
    cross_section,
    stats,
    watershed_segmentation,
    grain_analysis,
    fft_1d,
)
